
/*
 * Copyright (C) 2003-2016 eXo Platform SAS.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.exoplatform.outlook.rest;

import org.exoplatform.outlook.BadParameterException;
import org.exoplatform.outlook.OutlookException;
import org.exoplatform.outlook.jcr.ContentLink;
import org.exoplatform.outlook.jcr.NodeContent;
import org.exoplatform.services.log.ExoLogger;
import org.exoplatform.services.log.Log;
import org.exoplatform.services.rest.resource.ResourceContainer;

import javax.jcr.RepositoryException;
import javax.servlet.http.HttpServletRequest;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.ResponseBuilder;
import javax.ws.rs.core.Response.Status;
import javax.ws.rs.core.UriInfo;

/**
 * Created by The eXo Platform SAS
 * 
 * @author <a href="mailto:pnedonosko@exoplatform.com">Peter Nedonosko</a>
 * @version $Id: ContentService.java 00000 Aug 14, 2016 pnedonosko $
 * 
 */
@Path("/outlook")
public class ContentService implements ResourceContainer {

  protected static final Log  LOG = ExoLogger.getLogger(ContentService.class);

  protected final ContentLink contentLink;

  /**
   * 
   */
  public ContentService(ContentLink contentLink) {
    this.contentLink = contentLink;
  }

  /**
   * Document content download link. <br>
   * WARNING! It is publicly accessible service but access from the Documents Server host can be restricted
   * (by default).
   * 
   * @param uriInfo - request info
   * @param userId String
   * @param key - file key generated by {@link ContentLink#create(String, javax.jcr.Node)} method
   * @return {@link Response}
   */
  @GET
  @Path("/content/{userId}/{key}")
  public Response content(@Context UriInfo uriInfo,
                          @Context HttpServletRequest request,
                          @PathParam("userId") String userId,
                          @PathParam("key") String key) {
    String clientHost = getClientHost(request);
    String clientIp = getClientIpAddr(request);

    if (LOG.isDebugEnabled()) {
      LOG.debug("> Outlook document content: " + userId + "@" + key + " to " + clientHost + "(" + clientIp + ")");
    }
    ResponseBuilder resp;
    if (true) { // TODO editors.canDownloadBy(clientHost) || editors.canDownloadBy(clientIp)
      if (key != null && key.length() > 0) {
        try {
          if (userId != null && userId.length() > 0) {
            NodeContent content = contentLink.consume(userId, key);
            if (content != null) {
              resp = Response.ok().entity(content.getData()).type(content.getType());
            } else {
              resp = Response.status(Status.NOT_FOUND).entity("Content not found for " + key);
            }
          } else {
            LOG.error("Error downloading content. User identity not provided");
            resp = Response.status(Status.BAD_REQUEST).entity("User not provided");
          }
        } catch (BadParameterException e) {
          LOG.error("Bad parameter to downloading content for " + key, e);
          resp = Response.status(Status.BAD_REQUEST).entity(e.getMessage());
        } catch (OutlookException e) {
          LOG.error("Error downloading content for " + key, e);
          resp = Response.status(Status.INTERNAL_SERVER_ERROR).entity("Error downloading content. " + e.getMessage());
        } catch (RepositoryException e) {
          LOG.error("Storage error while downloading content for " + key, e);
          resp = Response.status(Status.INTERNAL_SERVER_ERROR).entity("Storage error.");
        } catch (Throwable e) {
          LOG.error("Runtime error while downloading content for " + key, e);
          resp = Response.status(Status.INTERNAL_SERVER_ERROR).entity("Runtime error.");
        }
      } else {
        resp = Response.status(Status.BAD_REQUEST).entity("Null or empty file key.");
      }
    } else {
      LOG.warn("Attempt to download content by not allowed host: " + clientHost);
      resp = Response.status(Status.UNAUTHORIZED).entity("Not a document server.");
    }
    return resp.build();
  }

  protected String getClientIpAddr(HttpServletRequest request) {
    String ip = request.getHeader("X-Forwarded-For");
    if (isValidName(ip)) {
      return ip;
    }
    ip = request.getHeader("Proxy-Client-IP");
    if (isValidName(ip)) {
      return ip;
    }
    ip = request.getHeader("WL-Proxy-Client-IP");
    if (isValidName(ip)) {
      return ip;
    }
    ip = request.getHeader("HTTP_CLIENT_IP");
    if (isValidName(ip)) {
      return ip;
    }
    ip = request.getHeader("HTTP_X_FORWARDED_FOR");
    if (isValidName(ip)) {
      return ip;
    }
    ip = request.getHeader("HTTP_X_FORWARDED");
    if (isValidName(ip)) {
      return ip;
    }
    ip = request.getHeader("HTTP_X_CLUSTER_CLIENT_IP");
    if (isValidName(ip)) {
      return ip;
    }
    // http://stackoverflow.com/questions/1634782/what-is-the-most-accurate-way-to-retrieve-a-users-correct-ip-address-in-php
    ip = request.getHeader("HTTP_FORWARDED_FOR");
    if (isValidName(ip)) {
      return ip;
    }
    ip = request.getHeader("HTTP_FORWARDED");
    if (isValidName(ip)) {
      return ip;
    }
    ip = request.getHeader("REMOTE_ADDR");
    if (isValidName(ip)) {
      return ip;
    }
    // last chance to get it from Servlet request
    ip = request.getRemoteAddr();
    if (isValidName(ip)) {
      return ip;
    }
    return null;
  }

  protected String getClientHost(HttpServletRequest request) {
    String host = request.getHeader("X-Forwarded-Host");
    if (isValidName(host)) {
      return host;
    }
    host = request.getRemoteHost();
    if (isValidName(host)) {
      return host;
    }
    return null;
  }

  protected boolean isValidName(String hostName) {
    if (hostName != null && hostName.length() > 0 && !"unknown".equalsIgnoreCase(hostName)) {
      return true;
    }
    return false;
  }

}
